### ISSUE TITLE
Licence for repository or data

### ISSUE THREAD

**Issue by ajmatas** [DanChitwood/Bio5702#1]
Dear Dan,
I would like use the candy dataset for a [short lecture](https://github.com/ajmatas/seminario_fenotipado_mentorac_2017) but I found no licence for the repository or the data within. Would it be possible to have a licence added to the repository that allows that use of the data? I'll of course include proper attribution and link back to this repository.

The content of the short lecture will be distributed under CC-BY and MIT licences.

Thank you,
Ant

**Comment by DanChitwood** [comment]
Dear Antonio,

Please, feel free to use the data, code, analysis, anything that you wish!

Sorry about the licenses. Honestly, I'm not that great with the legal
stuff. By never assigning a license it's not to restrict use, it's quite
the opposite . . . I just don't know enough and don't want to accidentally
make restrictive, so it actually means "go ahead and please do anything
that you like!"

Unfortunately, I was having some troubles online, so I deleted my previous
twitter account. But I had been tweeting along with the course, but those
tweets are gone now.

I taught this course with Chris Topp (ctopp@danforthcenter.org ) who did
more of the image analysis side, so he might be of use as well.

Glad to hear of the interest! I hope your own candy phenotyping goes well!!!

All the best,
Dan

**Comment by ajmatas** [comment]
Dear Dan,

Thank you very much for your generosity, and thank Chris too for sharing his work. When in doubt or missing a license, I always assume Copyright and ask the authors. For my work, not an expert neither, I'm using MIT License (for code) and CC-BY (for everything else).

Your data, code and introductory text was really helpful. I translated part of it to Spanish and it was a blast for secondary student to see how they can produce nice visualization from data during the seminar. This seminar is one of a series in a project with secondary education gifted students. I really enjoyed seeing very young girl and boys taking pictures, using ImageJ with them and making  histograms and boxplots with R.

I miss your Twitter updates quite a lot, and I told Margaret at PAG last month (we know each other from Cornell an reconnected with her thanks to your tweets).

Best wishes,
Ant
